---
driver:
  name: hyperv
  parent_vhd_folder: '../../output-hyperv-iso/virtual hard disks'
  parent_vhd_name: packer-hyperv-iso.vhdx

provisioner:
  name: chef_zero

transport:
  name: winrm
  elevated: true
  password: vagrant
  username: vagrant

platforms:
  - name: windows-2016

suites:
  - name: default
    run_list:
      - recipe[packer-templates::uninstall_powershell_ise]
      - recipe[packer-templates::install_ps_modules]
      - recipe[packer-templates::vbox_guest_additions]
      - recipe[packer-templates::delete_pagefile]
      - recipe[packer-templates::enable_file_sharing]
      - recipe[packer-templates::remote_desktop]
      - recipe[packer-templates::clean_sxs]
      - recipe[packer-templates::add_postunattend]
      - recipe[packer-templates::add_pagefile]
      - recipe[packer-templates::set_local_account_token_filter_policy]
      - recipe[packer-templates::remove_dirs]
    attributes:
